/*
 * Copyright 2010 Nick Aschman.
 */

package fr.curie.eftemtomoj.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.BevelBorder;
import java.awt.*;

/**
 * @author Nick Aschman
 */
class ProgressDialog extends JDialog {
    private JPanel contentPane;
    private JProgressBar progressBar;
    private JLabel progressLabel;

    public ProgressDialog(Dialog owner, String title) {
        super(owner, title);

        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
        setUndecorated(true);
        setMinimumSize(new Dimension(350, 80));

        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
    }

    public void show(String message) {
        progressLabel.setText("<html>" + message + "</html>");
        progressBar.setIndeterminate(true);

        setLocationRelativeTo(getParent());
        pack();
        setVisible(true);
    }

    public void setValue(double p) {
        progressBar.setValue((int) (p * 100));
        progressBar.setIndeterminate(false);
    }

    public void setMessage(String msg) {
        progressLabel.setText("<html>" + msg + "</html>");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBorder(new BevelBorder(BevelBorder.RAISED));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        progressLabel = new JLabel();
        progressLabel.setText("Label");
        panel1.add(progressLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        progressBar = new JProgressBar();
        panel1.add(progressBar, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    public static void main(String[] args) {
        ProgressDialog dlg = new ProgressDialog(null, "Progress");
        dlg.show("Test message");
    }
}
